"""empty message

Revision ID: 564e56536873
Revises: 5b1679f94f80
Create Date: 2024-10-07 21:21:10.888782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '564e56536873'
down_revision = '5b1679f94f80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seller',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seller')
    # ### end Alembic commands ###
