"""initial migration

Revision ID: d7378f710372
Revises: 
Create Date: 2024-10-24 20:02:18.492202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7378f710372'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sellers',
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('product',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('product_desc', sa.String(length=1000), nullable=False),
    sa.Column('product_img', sa.String(length=5000), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('seller_email', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['seller_email'], ['sellers.email'], ),
    sa.PrimaryKeyConstraint('pid')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.String(length=50), nullable=False),
    sa.Column('ordered_on', sa.DateTime(), nullable=False),
    sa.Column('payment_mode', sa.String(length=50), nullable=False),
    sa.Column('purchaser_name', sa.String(length=200), nullable=False),
    sa.Column('purchaser_mob', sa.String(length=100), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('review', sa.String(length=5000), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.pid'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('product')
    op.drop_table('sellers')
    # ### end Alembic commands ###
