from flask_sqlalchemy import SQLAlchemy
import datetime
from sqlalchemy.sql import func


db= SQLAlchemy()

class Product(db.Model):
    __tablename__ = 'product'
    pid = db.Column(db.Integer, primary_key=True)
    product_name = db.Column(db.String(200), nullable=False)
    product_desc = db.Column(db.String(1000), nullable=False)
    product_img = db.Column(db.String(5000), nullable = True)
    price = db.Column(db.Integer, nullable = False)
    seller_email = db.Column(db.String(100), db.ForeignKey("sellers.email"))
    orders =db.relationship('Orders', backref='product')
    seller = db.relationship('Seller', backref = 'product')

class Orders(db.Model):
    __tablename__='orders'
    order_id = db.Column(db.String(50), primary_key=True)# this id needs to be autogenerated once user completes purchase
    ordered_on = db.Column(db.DateTime(), nullable=False)
    payment_mode = db.Column(db.String(50), nullable = False)
    purchaser_name = db.Column(db.String(200), nullable=False)
    purchaser_mob = db.Column(db.String(100), nullable= False)
    product_id = db.Column(db.Integer, db.ForeignKey('product.pid'), nullable=True)
    review =  db.Column(db.String(5000), nullable = True)

class Seller(db.Model):
    __tablename__='sellers'
    email = db.Column(db.String(100), primary_key=True)
    password = db.Column(db.String(250), nullable=False)
    first_name = db.Column(db.String(100), nullable=False)
    last_name = db.Column(db.String(200), nullable=False)
    created_at = db.Column(db.DateTime(timezone=True), server_default = func.now())
    # product = db.relationship('Product', backref = 'sellers')

    
